buildpack: go_buildpack
memory: 256M
domain: app.cloud.gov
services:
- dashboard-ups
- dashboard-redis
env:
  CONSOLE_LOGIN_URL: https://login.fr.cloud.gov/
  CONSOLE_UAA_URL: https://uaa.fr.cloud.gov/
  CONSOLE_API_URL: https://api.fr.cloud.gov/
  CONSOLE_LOG_URL: https://loggregator.fr.cloud.gov/
  SECURE_COOKIES: true
  GA_TRACKING_ID: UA-48605964-34
  GOVERSION: go1.8
  GOPACKAGENAME: github.com/18F/cg-dashboard
  SESSION_BACKEND: redis
  BUILD_INFO: build::concourse::1.16.7::2017-07-10-20-25-27::::::::1.16.7