platform: linux
image_resource:
  type: docker-image
  source:
    repository: docker
    tag: 17.03-dind
inputs:
- name: cg-dashboard-source
outputs:
- name: cg-dashboard-compiled
run:
  dir: cg-dashboard-source
  path: ci/build.sh
