platform: linux
image_resource:
  type: docker-image
  source:
    repository: docker
    tag: 17.03-dind
inputs:
- name: cg-dashboard-source
run:
  # dir: cg-dashboard-source
  path: sh
  args:
  - -exc
  - |
    ls -al cg-dashboard-source
    cg-dashboard-source/ci/build.sh
