---
jobs:
- name: pull-status-check
  plan:
  - get: pull-request
    version: every
    trigger: true
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: build
    input_mapping:
      cg-dashboard-source: pull-request
    file: pull-request/ci/build.yml
    on_success:
      put: pull-request
      params:
        path: pull-request
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure

resources:
# - name: cg-dashboard-source
#   type: git
#   source:
#     uri: ((cg-dashboard-git-url))
#     branch: ((cg-dashboard-branch))

- name: pull-request
  type: pull-request
  source:
    repo: ((cg-dashboard-git-repo))
    access_token: ((status-access-token))
    every: true

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
